import {
  Activity,
  ClipboardCheck,
  ClipboardList,
  FileSearch,
  Globe2,
  HeartPulse,
  Microscope,
  Network,
  ShieldCheck,
  UserRound,
  UsersRound,
} from "lucide-react";

const assetPath = (path: string) => `${import.meta.env.BASE_URL}${path}`;

export type Language = "en" | "es";

export const languageOptions = [
  { code: "en", label: "EN", name: "English" },
  { code: "es", label: "ES", name: "Español" },
] as const;

export const siteContent = {
  en: {
    meta: {
      skipLink: "Skip to main content",
      homeAria: "Thera Research home",
      navAria: "Primary navigation",
      mobileNavAria: "Mobile navigation",
      closeMenu: "Close menu",
      openMenu: "Open menu",
      languageAria: "Select language",
      emailMenu: "Contact by email",
      linkedIn: "LinkedIn",
      headerCta: "Talk to a specialist",
      whatsapp: "WhatsApp",
    },
    navItems: [
      { label: "Company", page: "home" },
      { label: "Services", page: "services" },
      { label: "Patients", page: "patients" },
      { label: "Insights", page: "insights" },
      { label: "Contact", page: "contact" },
    ],
    pages: {
      home: {
        eyebrow: "Clinical research in Chile",
        heading: "Thera Research",
        copy: "Clinical trial management, site operations, monitoring, recruitment, and regulatory coordination for studies that need local ownership.",
      },
      services: {
        eyebrow: "Clinical operations",
        heading: "Study execution shaped around local sites.",
        copy: "A dedicated view of Thera Research services, workflow, monitoring, activation, and site coordination.",
        primaryCta: "Discuss a study",
        secondaryCta: "Patient recruitment",
      },
      patients: {
        eyebrow: "Patient recruitment",
        heading: "A clearer route for patients interested in studies.",
        copy: "Recruitment information and registration are separated into a focused page, with less noise and stronger orientation.",
        primaryCta: "Register interest",
        secondaryCta: "Contact Thera Research",
      },
      insights: {
        eyebrow: "Company activity",
        heading: "LinkedIn updates and current activity.",
        copy: "A dedicated page for official LinkedIn activity, company news, recruitment notices, and clinical research updates.",
        primaryCta: "Open LinkedIn",
        secondaryCta: "Contact team",
      },
      contact: {
        eyebrow: "Start a study",
        heading: "Connect with Thera Research.",
        copy: "A focused contact page for sponsors, study leads, and clinical teams planning local execution in Chile.",
        primaryCta: "Email Thera Research",
        secondaryCta: "View services",
      },
    },
    homeHub: {
      aria: "Thera Research site sections",
      eyebrow: "Study routes",
      heading: "A clearer structure for every clinical research moment.",
      copy: "Move directly into services, patient recruitment, current activity, or sponsor contact without searching through a single long page.",
      cta: "Open page",
    },
    credibility: {
      aria: "Thera Research operating record",
      intro: "Local ownership, measured against the work.",
      // PLACEHOLDER VALUES — replace each `value` with a figure Thera can defend publicly.
      stats: [
        { value: "[NN]+", label: "Studies coordinated", note: "Phases II–IV" },
        { value: "[NN]", label: "Sites activated in Chile", note: "Public and private" },
        { value: "[NN]", label: "Years operating locally", note: "Founded [YYYY]" },
        { value: "[NN]%", label: "On-time recruitment", note: "Last [NN] studies" },
      ],
      complianceLabel: "Standards & compliance",
      // PLACEHOLDER — keep only the credentials Thera can evidence on request.
      compliance: [
        "ICH-GCP",
        "ISP Chile authorization",
        "Accredited ethics committees",
        "ISO 9001 [if applicable]",
      ],
      sponsorsLabel: "Sponsors & partners",
      sponsorsNote: "Shown with sponsor permission.",
      // PLACEHOLDER — drop logo files in /public/assets/sponsors and list them here
      // as { src: "assets/sponsors/acme.svg", name: "Acme Pharma" }. Empty = placeholder slots.
      sponsors: [] as { src: string; name: string }[],
    },
    hero: {
      aria: "Thera Research",
      lead: "A Clinical Research Organization specialized in clinical trials management and full study support for pharmaceutical, biotechnology, generic drug, OTC/consumer healthcare, and medical device companies.",
      primaryCta: "Start a study",
      secondaryCta: "Patient recruitment",
    },
    studyPanel: {
      aria: "Clinical trial management summary",
      title: "Clinical trial management",
      footerLabel: "Study oversight",
      footerValue: "Startup through close-out",
    },
    intro: {
      eyebrow: "Our company",
      heading:
        "Clinical trial services for medical research studies in all diseases.",
      copy: "Thera Research provides flexibility in response to client outsourcing demands and assists throughout the clinical trial process, from site identification and strategic feasibility to activation, patient recruitment follow-up, site closure, and reporting.",
      imageAlt:
        "Regulatory dossier and clinical startup materials on a research desk",
    },
    services: {
      eyebrow: "Services",
      heading: "Support across the clinical trial process.",
      copy: "The service model covers site identification, feasibility, site selection, strategic partnerships, investigator qualification, activation, recruitment follow-up, and site closure.",
      deliverableLabel: "Deliverable",
      riskLabel: "Risk controlled",
    },
    capabilities: [
      {
        eyebrow: "01",
        title: "Site identification and feasibility",
        copy: "Country and site options are assessed before commitments are made, including strategic feasibility for the therapeutic area and study profile.",
        deliverable: "Site map, feasibility route, viability notes",
        risk: "Weak site fit",
        icon: FileSearch,
      },
      {
        eyebrow: "02",
        title: "Site selection and partnerships",
        copy: "Site selection, strategic site partnerships, and investigator dynamics are coordinated to support high-performing study execution.",
        deliverable: "Selected site list, partnership route, startup inputs",
        risk: "Low enrollment sites",
        icon: Network,
      },
      {
        eyebrow: "03",
        title: "Investigator qualifications",
        copy: "Investigator qualification is supported as part of startup, helping sponsors work with sites that match protocol and study demands.",
        deliverable:
          "Investigator review, qualification file, site readiness notes",
        risk: "Qualification gaps",
        icon: ShieldCheck,
      },
      {
        eyebrow: "04",
        title: "Regulatory activation and IMP import",
        copy: "Local regulatory submissions, site contracting, clinical startup, and IMP import coordination are facilitated through the study activation path.",
        deliverable:
          "Submission path, contract status, IMP import coordination",
        risk: "Activation delay",
        icon: ClipboardCheck,
      },
      {
        eyebrow: "05",
        title: "Patient recruitment follow-up",
        copy: "Recruitment follow-up is shaped around participant demographics, therapeutic area, site dynamics, and high-enrolling site potential.",
        deliverable: "Recruitment follow-up, enrollment signal, site support",
        risk: "Enrollment delay",
        icon: UsersRound,
      },
      {
        eyebrow: "06",
        title: "Site closure and reporting",
        copy: "Study close-out and reporting support preserve continuity after execution, keeping sponsor and site teams aligned through closure.",
        deliverable: "Closure package, reporting support, continuity notes",
        risk: "Closure friction",
        icon: Activity,
      },
    ],
    workflow: {
      eyebrow: "Workflow",
      heading: "One process from site identification to closure.",
      lead: "The operating line follows the current Thera Research service path: identification, feasibility, selection, activation, monitoring, recruitment follow-up, and site closure.",
      aria: "Study workflow checkpoints",
      steps: [
        {
          step: "Site identification",
          outcome:
            "Potential sites are identified against study needs, investigator dynamics, and local execution context.",
        },
        {
          step: "Strategic feasibility",
          outcome:
            "Feasibility is reviewed before commitments, with attention to timelines, participants, and sponsor expectations.",
        },
        {
          step: "Selection and qualification",
          outcome:
            "Site selection, strategic partnerships, and investigator qualifications are moved into a startup-ready route.",
        },
        {
          step: "Activation",
          outcome:
            "Local regulatory submissions, site contracting, clinical startup, and IMP import coordination advance the study.",
        },
        {
          step: "Monitoring and recruitment",
          outcome:
            "CRAs review data and compliance while recruitment follow-up tracks site dynamics and participant demographics.",
        },
        {
          step: "Site closure",
          outcome:
            "Site closure and reporting support keep sponsor and site teams aligned at the end of the study.",
        },
      ],
    },
    monitoring: {
      eyebrow: "Clinical trial monitoring",
      heading: "CRA oversight for data quality and site interaction.",
      copy: "Skilled and highly trained CRAs conduct on-site monitoring visits throughout the study, overseeing data collection, reviewing source documentation and case report forms, ensuring regulatory compliance, and resolving data queries requested by clients.",
      imageAlt:
        "Clinical research associate reviewing source documents and study files",
      overlayLabel: "On-site monitoring",
      overlayTitle: "CRA",
      overlayCopy:
        "Data collection, source documentation, CRFs, compliance, and query resolution.",
      signals: [
        "Oversee data collection",
        "Review source documentation and case report forms",
        "Ensure regulatory compliance",
        "Resolve data queries requested by clients",
      ],
    },
    operationsEvidence: {
      eyebrow: "Operational evidence",
      heading: "The study route is managed as a controlled operating system.",
      copy: "For sponsors, the value is not only task completion. It is the continuity between feasibility, regulatory startup, site behavior, monitoring, recruitment signal, and close-out evidence.",
      items: [
        {
          label: "Startup control",
          title: "Feasibility before commitments",
          copy: "Country and site options are reviewed against the therapeutic area, investigator dynamics, enrollment potential, and sponsor timeline.",
        },
        {
          label: "Regulatory line",
          title: "Submission and activation path",
          copy: "Local submissions, site contracts, clinical startup, and IMP import coordination remain connected to the study execution plan.",
        },
        {
          label: "Site intelligence",
          title: "Enrollment and monitoring signal",
          copy: "CRA oversight, participant demographics, site dynamics, and data queries are treated as operating signals, not isolated tasks.",
        },
      ],
      checks: [
        "Strategic feasibility",
        "Site qualification",
        "Regulatory startup",
        "CRA monitoring",
        "Recruitment follow-up",
        "Close-out reporting",
      ],
    },
    proof: {
      eyebrow: "Positioning",
      heading: "The CRO that takes responsibility.",
      support:
        "The current Thera Research message centers on responsibility, investigator knowledge, site dynamics, quality, audits, and long-term sponsor and site relationships.",
      primaryLabel: "Primary signal",
      supportingLabel: "Supporting signal",
      points: [
        {
          title: "Ownership from startup to close-out",
          copy: "Thera Research drives sponsor and site coordination with a process aimed at reducing study timelines and enhancing study success.",
          icon: ShieldCheck,
        },
        {
          title: "Medical research across diseases",
          copy: "Clinical trial services are offered for medical research studies in all diseases, with flexibility around outsourcing demands.",
          icon: Activity,
        },
        {
          title: "Site dynamics and enrollment",
          copy: "Knowledge of investigators, site dynamics, demographics, and high-enrolling sites supports efficient enrollment.",
          icon: Globe2,
        },
        {
          title: "Audits and regulatory experience",
          copy: "Experience includes internal and external audits, regulatory authority exposure, and inspection readiness.",
          icon: Microscope,
        },
      ],
    },
    patients: {
      eyebrow: "Patient recruitment",
      heading: "Enrollment support shaped around study demographics.",
      copy: "Thera Research understands participant demographics in each therapeutic area, how to enroll efficiently, how to identify high-enrolling sites, and how best to work with them.",
      cta: "Register interest",
    },
    linkedin: {
      eyebrow: "LinkedIn updates",
      heading: "Recent activity sourced from LinkedIn.",
      copy: "Public posts from the official Thera Research LinkedIn page, organized here as a readable news section with direct links to each update.",
      followHeading: "Follow the official company page",
      followCopy:
        "LinkedIn limits the full historical feed without sign-in. This page captures the public updates visible at the last review and keeps every item linked to its original post.",
      followFallback: "Follow Thera Research",
      filtersAria: "Filter LinkedIn updates",
      filters: [
        { id: "all", label: "All", match: [] },
        {
          id: "operations",
          label: "Operations",
          match: [
            "clinical operations",
            "protocol",
            "GCP",
            "CRA",
            "feasibility",
            "site",
            "regulatory",
            "data",
            "AI",
          ],
        },
        {
          id: "science",
          label: "Science",
          match: [
            "science",
            "basic research",
            "innovation",
            "immunology",
            "neuroscience",
            "TRIMELVax",
            "biotechnology",
          ],
        },
        {
          id: "patients",
          label: "Patients",
          match: [
            "patient",
            "participant",
            "cancer",
            "depression",
            "vaccines",
            "prevention",
          ],
        },
        {
          id: "company",
          label: "Company",
          match: [
            "company",
            "Thera Research",
            "partnership",
            "careers",
            "summit",
            "workshop",
            "ACROCHI",
          ],
        },
      ],
      visitPage: "Open LinkedIn page",
      featuredAria: "Featured LinkedIn updates",
      featuredLabel: "Featured updates",
      archiveLabel: "Full LinkedIn archive",
      postsAria: "LinkedIn post archive",
      sourceLabel: "Source",
      sourceValue: "Official LinkedIn public feed",
      reviewedLabel: "Checked",
      reviewedValue: "June 28, 2026",
      countLabel: "Visible posts",
      countValue: "30 captured",
      postCta: "Open post",
      imageLabel: "Image on LinkedIn",
      videoLabel: "Video on LinkedIn",
      reactionLabel: "reaction",
      reactionsLabel: "reactions",
      commentLabel: "comment",
      commentsLabel: "comments",
      posts: [
        {
          label: "Clinical operations",
          title: "Protocol literacy as a trust layer",
          date: "2 days on LinkedIn",
          copy: "A clinical operations note on why protocol understanding is shared language for investigators, coordinators, monitors, sponsors, ethics committees, and regulators.",
          reactions: "5",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicalresearch-clinicaltrials-clinicaloperations-activity-7476284354588241920-mL_j",
          tags: ["Protocol", "GCP", "Clinical operations"],
        },
        {
          label: "Public health",
          title: "Cervical cancer prevention is proven science",
          date: "4 days on LinkedIn",
          copy: "A prevention-focused update connecting vaccination, screening, early diagnosis, and the years of evidence needed before recommendations reach practice.",
          reactions: "6",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_hoy-sabemos-que-el-c%C3%A1ncer-cervicouterino-activity-7475518139435487232-9i9-",
          tags: ["Prevention", "Evidence", "Cancer"],
        },
        {
          label: "Science communication",
          title: "How science reaches people",
          date: "6 days on LinkedIn",
          copy: "A video conversation with Pablo Rosenblatt on the role of communication in science and why understanding is part of transformation.",
          reactions: "15",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_qu%C3%A9-hace-que-la-ciencia-realmente-llegue-activity-7474793324265078784-6xS_",
          tags: ["Science", "Communication", "Video"],
        },
        {
          label: "Research ethics",
          title: "Declaration of Helsinki",
          date: "1 week on LinkedIn",
          copy: "A bilingual reflection on informed consent, ethical review, and participant protection in human research.",
          reactions: "10",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_theraresearch-declarationofhelsinki-clinicalresearch-activity-7473049980174446592-GsEJ",
          tags: ["Ethics", "Participants", "Clinical research"],
        },
        {
          label: "Cancer research",
          title: "What clinical trials make possible",
          date: "1 week on LinkedIn",
          copy: "A Cancer Survivor Day video connecting today's treatments with the clinical studies that first tested whether those therapies worked.",
          reactions: "19",
          comments: "1",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_investigaci%C3%B3ncl%C3%ADnica-c%C3%A1ncer-salud-activity-7472366458505986048-ClBU",
          tags: ["Cancer", "Clinical trials", "Video"],
        },
        {
          label: "Basic science",
          title: "From question to discovery",
          date: "2 weeks on LinkedIn",
          copy: "A conversation with Mario Rosemblatt on how basic scientific questions can become discoveries with long-term health impact.",
          reactions: "22",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_ciencia-investigaci%C3%B3n-innovaci%C3%B3n-activity-7469719981434482689-K2Dg",
          tags: ["Science", "Innovation", "Biotechnology"],
        },
        {
          label: "Company activity",
          title: "Conversation with Dr. Mario Rosemblatt",
          date: "3 weeks on LinkedIn, edited",
          copy: "A company update announcing a discussion on basic science, immunology, and the research behind current health solutions.",
          reactions: "66",
          comments: "1",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_theraresearch-cienciab%C3%A1sica-investigaci%C3%B3n-activity-7468760527238864897-MlLI",
          tags: ["Thera Research", "Basic science", "Immunology"],
        },
        {
          label: "Clinical trials",
          title: "How modern clinical trials began",
          date: "3 weeks on LinkedIn",
          copy: "A short educational video on the historical path from early therapeutic questions to structured evidence in modern clinical studies.",
          reactions: "22",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_sab%C3%ADas-que-los-estudios-cl%C3%ADnicos-comenzaron-activity-7467183321459081216-Nhj9",
          tags: ["Clinical trials", "History", "Evidence"],
        },
        {
          label: "Neuroimmunology",
          title: "Parkinson's disease and immune research",
          date: "1 month on LinkedIn",
          copy: "A video post about Rodrigo Pacheco's work and how neuroimmunology is changing how Parkinson's disease progression is understood.",
          reactions: "36",
          comments: "2",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_neurociencia-inmunolog%C3%ADa-investigaci%C3%B3ncl%C3%ADnica-activity-7465378913473585152-n9KC",
          tags: ["Neuroscience", "Immunology", "Innovation"],
        },
        {
          label: "Ciencia Que Transforma",
          title: "Viruses, basic research, and health impact",
          date: "1 month on LinkedIn, edited",
          copy: "The first chapter of Ciencia Que Transforma highlights basic research, scientific collaboration, and the long route from discovery to public health impact.",
          reactions: "56",
          comments: "2",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_cienciaquetransforma-investigaci%C3%B3ncient%C3%ADfica-activity-7465115946353848320-CUuv",
          tags: ["Basic research", "Public health", "Science"],
        },
        {
          label: "Clinical research ecosystem",
          title: "AMIIF Clinical Research Summit",
          date: "1 month on LinkedIn",
          copy: "A repost from the AMIIF summit on operational capacity, connected institutions, efficient processes, and collaborative models for clinical research.",
          reactions: "36",
          comments: "2",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_investigaci%C3%B3ncl%C3%ADnica-ensayoscl%C3%ADnicos-chile-activity-7461090021736067072-Gi6N",
          tags: ["Clinical research", "Innovation", "Ecosystem"],
        },
        {
          label: "Translational science",
          title: "TRIMELVax and Chilean clinical development",
          date: "1 month on LinkedIn, edited",
          copy: "A note connecting TRIMELVax results with the bridge from basic science to real, regulated, well-designed clinical execution.",
          reactions: "45",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_hace-unos-d%C3%ADas-el-10-de-abril-tuve-la-oportunidad-activity-7460362410928009216-vivw",
          tags: ["TRIMELVax", "Clinical development", "Chile"],
        },
        {
          label: "Patient-centered research",
          title: "The people behind clinical research",
          date: "1 month on LinkedIn",
          copy: "A human-centered reminder that every data point connects to patients, study teams, and professionals working with rigor and commitment.",
          reactions: "12",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_clinicalresearch-investigacionclinica-activity-7460297964809281536-aOb6",
          tags: ["Patients", "Teams", "Clinical research"],
        },
        {
          label: "Partnerships",
          title: "BUPA visit to Ciencia & Vida",
          date: "1 month on LinkedIn, edited",
          copy: "An ecosystem update from the visit of BUPA executives to Fundacion Ciencia & Vida and Thera Research offices, focused on recruitment, collaboration, and regional clinical research.",
          reactions: "",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_clinicalresearch-healthcareinnovation-activity-7457848363489624064-heTb",
          tags: ["Partnerships", "Healthcare innovation", "LatAm"],
        },
        {
          label: "Clinical trials",
          title: "Clinical Trials Day and health innovation",
          date: "1 month on LinkedIn",
          copy: "A recognition of the curiosity, rigor, participants, investigators, sponsors, sites, and teams behind clinical trials.",
          reactions: "14",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicaltrialsday-clinicalresearch-clinicaltrials-activity-7462952560190992386-hunF",
          tags: ["Clinical Trials Day", "Evidence", "Healthcare innovation"],
        },
        {
          label: "Evidence",
          title: "Data becomes insight through context",
          date: "1 month on LinkedIn",
          copy: "A short clinical operations post on why data alone is not enough and how context connects evidence to real-world execution.",
          reactions: "10",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicaltrials-clinicalresearch-pharma-activity-7455590551388737536-bsSF",
          tags: ["Data", "Clinical operations", "Pharma"],
        },
        {
          label: "Study timelines",
          title: "Faster trials need alignment",
          date: "2 months on LinkedIn",
          copy: "A concise note on feasibility, realistic protocols, and site engagement as the operating ingredients behind better study timelines.",
          reactions: "25",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicaltrials-clinicalresearch-cro-activity-7453442684721180672-yQuV",
          tags: ["Feasibility", "Timelines", "Site engagement"],
        },
        {
          label: "Public-private collaboration",
          title: "CORFO vision workshop",
          date: "2 months on LinkedIn",
          copy: "A company update from the biomedical research vision workshop organized by CORFO's Transforma Innovacion en Salud program.",
          reactions: "21",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicaltrials-chile-innovation-activity-7452075324173000704-I5C6",
          tags: ["Chile", "Innovation", "Public-private"],
        },
        {
          label: "Health innovation",
          title: "PULSO and multidisciplinary innovation",
          date: "2 months on LinkedIn",
          copy: "A reflection from PULSO on how health innovation also depends on design, communication, patient connection, and multidisciplinary work.",
          reactions: "14",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_innovation-health-clinicalresearch-activity-7452079134719156224-jrBS",
          tags: ["Innovation", "Patient centricity", "Chile"],
        },
        {
          label: "AI and regulation",
          title: "AI in clinical trials",
          date: "2 months on LinkedIn",
          copy: "A regulatory note on traceability, validation, and data protection as artificial intelligence enters clinical trial workflows.",
          reactions: "4",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicaltrials-ai-clinicalresearch-activity-7452063570571444224-HnXJ",
          tags: ["AI", "Regulatory", "Clinical trials"],
        },
        {
          label: "Company activity",
          title: "New Year 2025",
          date: "1 year on LinkedIn",
          copy: "A company greeting for 2025, with continued focus on clinical trials, medical innovation, patient-centered work, and ethical research.",
          reactions: "5",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_newyear2025-clinicaltrials-medicalinnovation-activity-7279860081645481985-EFWe",
          tags: ["Company", "Clinical trials", "Medical innovation"],
        },
        {
          label: "Mental health",
          title: "World Day for the Fight Against Depression",
          date: "1 year on LinkedIn",
          copy: "A mental health awareness post on the role of clinical trials in developing therapies, tools, and new options for depression.",
          reactions: "1",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_worlddayagainstdepression-mentalhealth-activity-7284555486945816577-4gWh",
          tags: ["Mental health", "Clinical trials", "Awareness"],
        },
        {
          label: "CRA practice",
          title: "10 key tips to excel as a CRA",
          date: "1 year on LinkedIn",
          copy: "Practical content for clinical research associates on protocols, compliance, site relationships, proactive problem solving, and patient safety.",
          reactions: "",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_10-key-tips-to-excel-as-a-cra-in-clinical-activity-7270506239611043840-hcK1",
          tags: ["CRA", "Clinical operations", "Patient safety"],
        },
        {
          label: "Participant education",
          title: "What happens after trial participation ends",
          date: "1 year on LinkedIn",
          copy: "Educational content for participants on health follow-up, access to study results, confidentiality, and contribution to future treatments.",
          reactions: "1",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_theraresearch-clinicaltrials-activity-7267634428154195969-0jOs",
          tags: ["Participants", "Follow-up", "Clinical trials"],
        },
        {
          label: "Careers",
          title: "Clinical Research Associate opening",
          date: "1 year on LinkedIn",
          copy: "A recruitment post for a CRA II, CRA III, or Senior CRA role, focused on remote-based clinical trial monitoring experience.",
          reactions: "39",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_ofertadetrabajo-cra-clinicaltrials-activity-7233919781895090177-B_Rq",
          tags: ["Careers", "CRA", "Clinical trials"],
        },
        {
          label: "Oncology",
          title: "What is lung cancer and why does it matter",
          date: "1 year on LinkedIn",
          copy: "A health awareness post on lung cancer in Chile, observational studies, computational models, and adaptive trials.",
          reactions: "5",
          comments: "1",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_what-is-the-most-common-type-of-cancer-activity-7230322439262552064-_GHw",
          tags: ["Lung cancer", "Oncology", "Adaptive trials"],
        },
        {
          label: "Clinical trials",
          title: "International Clinical Trials Day 2024",
          date: "2 years on LinkedIn",
          copy: "A recognition of patients and professionals who make clinical trials possible and help advance new treatments.",
          reactions: "3",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_internationalclinicaltrialsday-healthinnovation-activity-7198454004593422336-B8Xw",
          tags: ["Clinical trials", "Health innovation", "Participants"],
        },
        {
          label: "Education",
          title: "The roles in clinical trials",
          date: "2 years on LinkedIn",
          copy: "Educational content explaining the work of principal investigators, co-investigators, coordinators, and clinical research associates.",
          reactions: "8",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_the-roles-in-clinical-trials-activity-7193671354313756673-L30W",
          tags: ["Education", "Study teams", "Clinical trials"],
        },
        {
          label: "Vaccines",
          title: "How vaccines are developed",
          date: "2 years on LinkedIn",
          copy: "A Vaccination Week in the Americas post explaining preclinical evaluation, immune response, animal studies, and human clinical trial phases.",
          reactions: "4",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_vaccines-clinicaltrials-theraresearch-activity-7188570332130091010-J4Q7",
          tags: ["Vaccines", "Clinical trials", "PAHO"],
        },
        {
          label: "Good Clinical Practice",
          title: "ACROCHI Good Clinical Practices course",
          date: "5 years on LinkedIn",
          copy: "A training update for ACROCHI's Good Clinical Practices online course, with Ximena Verdina participating as speaker on ethics committees.",
          reactions: "16",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_acrochi-clinicaltrials-clinicalresearch-activity-6729098011470823424--6sX",
          tags: ["GCP", "ACROCHI", "Ethics committees"],
        },
      ],
    },
    patientRegistration: {
      aria: "Patient recruitment registration",
      eyebrow: "Patient recruitment",
      heading: "Registration for patients interested in clinical studies.",
      copy: "Complete these details so the Thera Research team can review your inquiry and contact you by phone or email.",
      stepsAria: "Registration information requested",
      steps: [
        {
          icon: UserRound,
          title: "Personal details",
          copy: "First name, last name, phone number, and city of residence.",
        },
        {
          icon: HeartPulse,
          title: "Clinical background",
          copy: "Cancer diagnosis status and patient-provided diagnosis details.",
        },
        {
          icon: ClipboardList,
          title: "Authorization",
          copy: "Explicit permission for the team to contact the patient.",
        },
      ],
      formAria: "Patient recruitment form",
      fields: {
        firstName: {
          label: "First name",
          error: "Enter your first name.",
        },
        lastName: {
          label: "Last name",
          error: "Enter your last name.",
        },
        phone: {
          label: "Phone",
          error: "Enter a contact phone number.",
        },
        city: {
          label: "City of residence",
          error: "Enter your city.",
        },
        diagnosed: {
          label: "Have you been diagnosed with cancer?",
          yes: "Yes",
          no: "No",
          error: "Select an answer.",
        },
        diagnosis: {
          label: "What is your cancer diagnosis?",
          error: "Enter the diagnosis provided to you.",
        },
        consent: {
          label:
            "I authorize Thera Research to contact me and send information by email or phone.",
          error: "You must authorize contact to submit the registration.",
        },
      },
      status: {
        loadingLabel: "Submitting registration",
        empty: "Required fields must be completed before submitting.",
        error: "Complete the required information.",
        success:
          "Registration submitted. The Thera Research team will be able to review your information.",
      },
      submit: "Submit registration",
      iframeTitle: "Patient recruitment submission",
    },
    operatingSignals: [
      { label: "Operating model", value: "Local site coordination" },
      {
        label: "Sponsor sectors",
        value: "Pharma, biotech, generics, OTC, devices",
      },
      { label: "Study scope", value: "Planning, running, reporting" },
      { label: "Regulatory line", value: "Submissions and startup" },
    ],
    contact: {
      eyebrow: "Contact",
      heading: "Start your next clinical study with Thera Research.",
      copy: "Contact a team built to drive sponsor and site coordination, with the goal of reduced study timelines and enhanced study success.",
    },
    contactForm: {
      aria: "Clinical study contact request",
      fields: {
        name: {
          label: "Name",
          placeholder: "Sponsor or study lead",
          hint: "Used only to identify the contact request.",
          error: "Enter your name.",
        },
        email: {
          label: "Email",
          placeholder: "name@company.com",
          hint: "Corporate contact recommended.",
          error: "Enter a valid email address.",
        },
        message: {
          label: "Study context",
          placeholder:
            "Therapeutic area, sites, timeline, or recruitment needs",
          hint: "Include the minimum useful scope for feasibility review.",
          error: "Add the study context.",
        },
      },
      status: {
        loadingLabel: "Preparing contact request",
        empty:
          "Complete the fields to prepare a clinical study contact request.",
        error: "All fields are required to prepare the request.",
        success:
          "Contact request prepared. Connect this form to CRM or email next.",
      },
      submit: "Prepare request",
    },
    footer: {
      copy: "Clinical Research Organization supporting planning, execution, reporting, monitoring, regulatory coordination, and patient recruitment.",
      label: "Clinical research organization",
      ctaEyebrow: "Local clinical execution",
      ctaHeading: "Plan the next study route with Thera Research.",
      ctaCopy:
        "Start with the study context, recruitment needs, sites, or timeline that need local ownership in Chile.",
      primaryCta: "Start a study",
      secondaryCta: "Follow activity",
      routesLabel: "Site sections",
      contactLabel: "Direct contact",
      sourceLabel: "Current activity",
      sourceCopy: "LinkedIn updates, company news, and clinical research notes.",
      legal: "Thera Research Ltda. Clinical research operations in Chile.",
    },
  },
  es: {
    meta: {
      skipLink: "Saltar al contenido principal",
      homeAria: "Inicio de Thera Research",
      navAria: "Navegación principal",
      mobileNavAria: "Navegación móvil",
      closeMenu: "Cerrar menú",
      openMenu: "Abrir menú",
      languageAria: "Seleccionar idioma",
      emailMenu: "Contactar por correo",
      linkedIn: "LinkedIn",
      headerCta: "Hablar con un especialista",
      whatsapp: "WhatsApp",
    },
    navItems: [
      { label: "Empresa", page: "home" },
      { label: "Servicios", page: "services" },
      { label: "Pacientes", page: "patients" },
      { label: "Noticias", page: "insights" },
      { label: "Contacto", page: "contact" },
    ],
    pages: {
      home: {
        eyebrow: "Investigación clínica en Chile",
        heading: "Thera Research",
        copy: "Gestión de estudios clínicos, operación de centros, monitoreo, reclutamiento y coordinación regulatoria para estudios que necesitan responsabilidad local.",
      },
      services: {
        eyebrow: "Operación clínica",
        heading: "Ejecución de estudios según la realidad local de centros.",
        copy: "Una vista dedicada a servicios, flujo operativo, monitoreo, activación y coordinación de centros de Thera Research.",
        primaryCta: "Conversar un estudio",
        secondaryCta: "Reclutamiento de pacientes",
      },
      patients: {
        eyebrow: "Reclutamiento de pacientes",
        heading: "Una ruta más clara para pacientes interesados en estudios.",
        copy: "La información de reclutamiento y el registro quedan separados en una página enfocada, con menos ruido y mejor orientación.",
        primaryCta: "Registrar interés",
        secondaryCta: "Contactar a Thera Research",
      },
      insights: {
        eyebrow: "Actividad de empresa",
        heading: "Actualizaciones de LinkedIn y actividad reciente.",
        copy: "Una página dedicada a actividad oficial en LinkedIn, noticias de empresa, avisos de reclutamiento y actualizaciones de investigación clínica.",
        primaryCta: "Abrir LinkedIn",
        secondaryCta: "Contactar equipo",
      },
      contact: {
        eyebrow: "Iniciar un estudio",
        heading: "Conecta con Thera Research.",
        copy: "Una página de contacto enfocada para patrocinadores, líderes de estudio y equipos clínicos que planifican ejecución local en Chile.",
        primaryCta: "Enviar correo",
        secondaryCta: "Ver servicios",
      },
    },
    homeHub: {
      aria: "Secciones del sitio Thera Research",
      eyebrow: "Rutas de estudio",
      heading: "Una estructura más clara para cada momento de investigación clínica.",
      copy: "Avance directo a servicios, reclutamiento de pacientes, actividad reciente o contacto con patrocinadores sin recorrer una sola página larga.",
      cta: "Abrir página",
    },
    credibility: {
      aria: "Trayectoria operativa de Thera Research",
      intro: "Responsabilidad local, medida contra el trabajo.",
      // VALORES PLACEHOLDER — reemplaza cada `value` por una cifra que Thera pueda sostener públicamente.
      stats: [
        { value: "[NN]+", label: "Estudios coordinados", note: "Fases II–IV" },
        { value: "[NN]", label: "Centros activados en Chile", note: "Públicos y privados" },
        { value: "[NN]", label: "Años de operación local", note: "Desde [AAAA]" },
        { value: "[NN]%", label: "Reclutamiento a tiempo", note: "Últimos [NN] estudios" },
      ],
      complianceLabel: "Estándares y cumplimiento",
      // PLACEHOLDER — deja solo las credenciales que Thera pueda evidenciar a solicitud.
      compliance: [
        "ICH-GCP",
        "Autorización ISP Chile",
        "Comités de ética acreditados",
        "ISO 9001 [si aplica]",
      ],
      sponsorsLabel: "Patrocinadores y aliados",
      sponsorsNote: "Mostrados con autorización del patrocinador.",
      // PLACEHOLDER — coloca los logos en /public/assets/sponsors y lístalos aquí
      // como { src: "assets/sponsors/acme.svg", name: "Acme Pharma" }. Vacío = ranuras placeholder.
      sponsors: [] as { src: string; name: string }[],
    },
    hero: {
      aria: "Thera Research",
      lead: "Una organización de investigación clínica (CRO) especializada en la gestión de estudios clínicos y soporte integral para compañías farmacéuticas, biotecnológicas, de medicamentos genéricos, productos OTC/salud de consumo y dispositivos médicos.",
      primaryCta: "Iniciar un estudio",
      secondaryCta: "Reclutamiento de pacientes",
    },
    studyPanel: {
      aria: "Resumen de gestión de estudios clínicos",
      title: "Gestión de estudios clínicos",
      footerLabel: "Supervisión del estudio",
      footerValue: "Desde puesta en marcha hasta cierre",
    },
    intro: {
      eyebrow: "Nuestra empresa",
      heading:
        "Servicios de estudios clínicos para investigación médica en todas las enfermedades.",
      copy: "Thera Research ofrece flexibilidad frente a las necesidades de outsourcing de sus clientes y acompaña todo el proceso del estudio clínico, desde la identificación de centros y la factibilidad estratégica hasta la activación, el seguimiento del reclutamiento de pacientes, el cierre de centros y los informes.",
      imageAlt:
        "Dossier regulatorio y materiales de puesta en marcha clínica sobre una mesa de investigación",
    },
    services: {
      eyebrow: "Servicios",
      heading: "Soporte a lo largo del proceso del estudio clínico.",
      copy: "El modelo de servicio cubre identificación de centros, factibilidad, selección de centros, alianzas estratégicas, calificación de investigadores, activación, seguimiento del reclutamiento y cierre de centros.",
      deliverableLabel: "Entregable",
      riskLabel: "Riesgo controlado",
    },
    capabilities: [
      {
        eyebrow: "01",
        title: "Identificación de centros y factibilidad",
        copy: "Las opciones de país y centros se evalúan antes de asumir compromisos, incluyendo factibilidad estratégica para el área terapéutica y el perfil del estudio.",
        deliverable:
          "Mapa de centros, ruta de factibilidad, notas de viabilidad",
        risk: "Bajo ajuste del centro",
        icon: FileSearch,
      },
      {
        eyebrow: "02",
        title: "Selección de centros y alianzas",
        copy: "La selección de centros, las alianzas estratégicas y la dinámica con investigadores se coordinan para apoyar una ejecución de alto desempeño.",
        deliverable:
          "Lista de centros, ruta de alianzas, insumos de puesta en marcha",
        risk: "Centros con bajo enrolamiento",
        icon: Network,
      },
      {
        eyebrow: "03",
        title: "Calificación de investigadores",
        copy: "La calificación de investigadores se apoya como parte de la puesta en marcha, ayudando a los patrocinadores a trabajar con centros alineados al protocolo y a las exigencias del estudio.",
        deliverable:
          "Revisión de investigador, archivo de calificación, notas de preparación",
        risk: "Brechas de calificación",
        icon: ShieldCheck,
      },
      {
        eyebrow: "04",
        title:
          "Activación regulatoria e importación de producto investigacional",
        copy: "Las presentaciones regulatorias locales, los contratos con centros, la puesta en marcha clínica y la coordinación de importación de producto investigacional se facilitan dentro de la ruta de activación del estudio.",
        deliverable:
          "Ruta de presentación, estado contractual, coordinación de producto investigacional",
        risk: "Retraso en activación",
        icon: ClipboardCheck,
      },
      {
        eyebrow: "05",
        title: "Seguimiento del reclutamiento de pacientes",
        copy: "El seguimiento del reclutamiento se define según demografía de participantes, área terapéutica, dinámica de centros y potencial de centros de alto enrolamiento.",
        deliverable:
          "Seguimiento de reclutamiento, señal de enrolamiento, soporte al centro",
        risk: "Retraso en enrolamiento",
        icon: UsersRound,
      },
      {
        eyebrow: "06",
        title: "Cierre de centros e informes",
        copy: "El soporte de cierre e informes mantiene la continuidad después de la ejecución, alineando a patrocinadores y equipos de centros hasta el cierre.",
        deliverable:
          "Paquete de cierre, soporte de informes, notas de continuidad",
        risk: "Fricción de cierre",
        icon: Activity,
      },
    ],
    workflow: {
      eyebrow: "Flujo",
      heading: "Un proceso desde la identificación de centros hasta el cierre.",
      lead: "La operación sigue la ruta actual de servicios de Thera Research: identificación, factibilidad, selección, activación, monitoreo, seguimiento de reclutamiento y cierre de centros.",
      aria: "Hitos del flujo del estudio",
      steps: [
        {
          step: "Identificación de centros",
          outcome:
            "Los centros potenciales se identifican según las necesidades del estudio, la dinámica de investigadores y el contexto local de ejecución.",
        },
        {
          step: "Factibilidad estratégica",
          outcome:
            "La factibilidad se revisa antes de asumir compromisos, con foco en plazos, participantes y expectativas del patrocinador.",
        },
        {
          step: "Selección y calificación",
          outcome:
            "La selección de centros, las alianzas estratégicas y la calificación de investigadores avanzan hacia una ruta lista para la puesta en marcha.",
        },
        {
          step: "Activación",
          outcome:
            "Las presentaciones regulatorias locales, los contratos con centros, la puesta en marcha clínica y la coordinación de importación de producto investigacional impulsan el estudio.",
        },
        {
          step: "Monitoreo y reclutamiento",
          outcome:
            "Los CRA revisan datos y cumplimiento mientras el seguimiento del reclutamiento observa la dinámica de centros y la demografía de participantes.",
        },
        {
          step: "Cierre de centros",
          outcome:
            "El cierre de centros y el soporte de informes mantienen alineados a patrocinadores y equipos de centros al final del estudio.",
        },
      ],
    },
    monitoring: {
      eyebrow: "Monitoreo de estudios clínicos",
      heading:
        "Supervisión CRA para calidad de datos e interacción con centros.",
      copy: "CRA capacitados y con alta preparación realizan visitas de monitoreo en terreno durante el estudio, supervisando la recolección de datos, revisando documentación fuente y formularios de reporte de caso, asegurando cumplimiento regulatorio y resolviendo consultas de datos solicitadas por los clientes.",
      imageAlt:
        "Clinical research associate revisando documentación fuente y archivos del estudio",
      overlayLabel: "Monitoreo en terreno",
      overlayTitle: "CRA",
      overlayCopy:
        "Recolección de datos, documentación fuente, CRF, cumplimiento y resolución de consultas.",
      signals: [
        "Supervisión de recolección de datos",
        "Revisión de documentación fuente y formularios de reporte de caso",
        "Aseguramiento de cumplimiento regulatorio",
        "Resolución de consultas de datos solicitadas por clientes",
      ],
    },
    operationsEvidence: {
      eyebrow: "Evidencia operativa",
      heading: "La ruta del estudio se gestiona como un sistema operativo controlado.",
      copy: "Para patrocinadores, el valor no es solo completar tareas. Es mantener continuidad entre factibilidad, puesta en marcha regulatoria, comportamiento de centros, monitoreo, señal de reclutamiento y evidencia de cierre.",
      items: [
        {
          label: "Control de startup",
          title: "Factibilidad antes de compromisos",
          copy: "Las opciones de país y centros se revisan según área terapéutica, dinámica de investigadores, potencial de enrolamiento y plazos del patrocinador.",
        },
        {
          label: "Línea regulatoria",
          title: "Ruta de presentación y activación",
          copy: "Presentaciones locales, contratos con centros, puesta en marcha clínica y coordinación de importación se conectan al plan de ejecución.",
        },
        {
          label: "Inteligencia de centros",
          title: "Señal de enrolamiento y monitoreo",
          copy: "La supervisión CRA, demografía de participantes, dinámica de centros y queries se tratan como señales operativas, no como tareas aisladas.",
        },
      ],
      checks: [
        "Factibilidad estratégica",
        "Calificación de centros",
        "Startup regulatorio",
        "Monitoreo CRA",
        "Seguimiento de reclutamiento",
        "Informes de cierre",
      ],
    },
    proof: {
      eyebrow: "Posicionamiento",
      heading: "La CRO que toma responsabilidad.",
      support:
        "El mensaje actual de Thera Research se centra en responsabilidad, conocimiento de investigadores, dinámica de centros, calidad, auditorías y relaciones de largo plazo con patrocinadores y centros.",
      primaryLabel: "Señal principal",
      supportingLabel: "Señal de apoyo",
      points: [
        {
          title: "Responsabilidad desde la puesta en marcha hasta el cierre",
          copy: "Thera Research impulsa la coordinación entre patrocinador y centro con un proceso orientado a reducir plazos y mejorar el éxito del estudio.",
          icon: ShieldCheck,
        },
        {
          title: "Investigación médica en distintas enfermedades",
          copy: "Los servicios de estudios clínicos se ofrecen para investigación médica en todas las enfermedades, con flexibilidad frente a necesidades de outsourcing.",
          icon: Activity,
        },
        {
          title: "Dinámica de centros y enrolamiento",
          copy: "El conocimiento de investigadores, dinámica de centros, demografía y centros de alto enrolamiento apoya un enrolamiento eficiente.",
          icon: Globe2,
        },
        {
          title: "Auditorías y experiencia regulatoria",
          copy: "La experiencia incluye auditorías internas y externas, exposición a autoridad regulatoria y preparación para inspecciones.",
          icon: Microscope,
        },
      ],
    },
    patients: {
      eyebrow: "Reclutamiento de pacientes",
      heading: "Soporte de enrolamiento según la demografía del estudio.",
      copy: "Thera Research entiende la demografía de participantes en cada área terapéutica, cómo enrolar con eficiencia, cómo identificar centros de alto enrolamiento y cómo trabajar mejor con ellos.",
      cta: "Registrar interés",
    },
    linkedin: {
      eyebrow: "Actualizaciones en LinkedIn",
      heading: "Actividad reciente obtenida desde LinkedIn.",
      copy: "Publicaciones públicas de la página oficial de Thera Research en LinkedIn, organizadas aquí como una sección de noticias con enlaces directos a cada actualización.",
      followHeading: "Sigue la página oficial de la empresa",
      followCopy:
        "LinkedIn limita el histórico completo sin inicio de sesión. Esta página captura las actualizaciones públicas visibles en la última revisión y mantiene cada ítem enlazado a su publicación original.",
      followFallback: "Seguir a Thera Research",
      filtersAria: "Filtrar actualizaciones de LinkedIn",
      filters: [
        { id: "all", label: "Todo", match: [] },
        {
          id: "operations",
          label: "Operación",
          match: [
            "operación",
            "protocolo",
            "BPC",
            "CRA",
            "factibilidad",
            "centro",
            "regulatoria",
            "datos",
            "IA",
          ],
        },
        {
          id: "science",
          label: "Ciencia",
          match: [
            "ciencia",
            "ciencia básica",
            "innovación",
            "inmunología",
            "neurociencia",
            "TRIMELVax",
            "biotecnología",
          ],
        },
        {
          id: "patients",
          label: "Pacientes",
          match: [
            "paciente",
            "participante",
            "cáncer",
            "depresión",
            "vacunas",
            "prevención",
          ],
        },
        {
          id: "company",
          label: "Empresa",
          match: [
            "empresa",
            "Thera Research",
            "alianzas",
            "oferta",
            "summit",
            "workshop",
            "ACROCHI",
          ],
        },
      ],
      visitPage: "Abrir página de LinkedIn",
      featuredAria: "Actualizaciones destacadas de LinkedIn",
      featuredLabel: "Actualizaciones destacadas",
      archiveLabel: "Archivo completo de LinkedIn",
      postsAria: "Archivo de publicaciones de LinkedIn",
      sourceLabel: "Fuente",
      sourceValue: "Feed público oficial de LinkedIn",
      reviewedLabel: "Revisado",
      reviewedValue: "28 de junio de 2026",
      countLabel: "Publicaciones visibles",
      countValue: "30 capturadas",
      postCta: "Abrir publicación",
      imageLabel: "Imagen en LinkedIn",
      videoLabel: "Video en LinkedIn",
      reactionLabel: "reacción",
      reactionsLabel: "reacciones",
      commentLabel: "comentario",
      commentsLabel: "comentarios",
      posts: [
        {
          label: "Operación clínica",
          title: "El protocolo como capa de confianza",
          date: "Hace 2 días en LinkedIn",
          copy: "Una nota de operación clínica sobre por qué entender el protocolo es un lenguaje común para investigadores, coordinadores, monitores, patrocinadores, comités de ética y reguladores.",
          reactions: "5",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicalresearch-clinicaltrials-clinicaloperations-activity-7476284354588241920-mL_j",
          tags: ["Protocolo", "BPC", "Operación clínica"],
        },
        {
          label: "Salud pública",
          title: "La prevención del cáncer cervicouterino es ciencia probada",
          date: "Hace 4 días en LinkedIn",
          copy: "Una actualización sobre prevención que conecta vacunación, tamizaje, diagnóstico temprano y los años de evidencia necesarios antes de llegar a la práctica.",
          reactions: "6",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_hoy-sabemos-que-el-c%C3%A1ncer-cervicouterino-activity-7475518139435487232-9i9-",
          tags: ["Prevención", "Evidencia", "Cáncer"],
        },
        {
          label: "Comunicación científica",
          title: "Cómo la ciencia llega a las personas",
          date: "Hace 6 días en LinkedIn",
          copy: "Una conversación en video con Pablo Rosenblatt sobre el rol de la comunicación en ciencia y por qué entender también es parte de transformar.",
          reactions: "15",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_qu%C3%A9-hace-que-la-ciencia-realmente-llegue-activity-7474793324265078784-6xS_",
          tags: ["Ciencia", "Comunicación", "Video"],
        },
        {
          label: "Ética de investigación",
          title: "Declaración de Helsinki",
          date: "Hace 1 semana en LinkedIn",
          copy: "Una reflexión bilingüe sobre consentimiento informado, revisión ética y protección de participantes en investigación con seres humanos.",
          reactions: "10",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_theraresearch-declarationofhelsinki-clinicalresearch-activity-7473049980174446592-GsEJ",
          tags: ["Ética", "Participantes", "Investigación clínica"],
        },
        {
          label: "Investigación en cáncer",
          title: "Lo que hacen posible los estudios clínicos",
          date: "Hace 1 semana en LinkedIn",
          copy: "Un video del día del sobreviviente de cáncer que conecta los tratamientos actuales con los estudios clínicos que primero probaron si esas terapias funcionaban.",
          reactions: "19",
          comments: "1",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_investigaci%C3%B3ncl%C3%ADnica-c%C3%A1ncer-salud-activity-7472366458505986048-ClBU",
          tags: ["Cáncer", "Estudios clínicos", "Video"],
        },
        {
          label: "Ciencia básica",
          title: "De una pregunta a un descubrimiento",
          date: "Hace 2 semanas en LinkedIn",
          copy: "Una conversación con Mario Rosemblatt sobre cómo las preguntas de ciencia básica pueden transformarse en descubrimientos con impacto en salud.",
          reactions: "22",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_ciencia-investigaci%C3%B3n-innovaci%C3%B3n-activity-7469719981434482689-K2Dg",
          tags: ["Ciencia", "Innovación", "Biotecnología"],
        },
        {
          label: "Actividad de empresa",
          title: "Conversación con el Dr. Mario Rosemblatt",
          date: "Hace 3 semanas en LinkedIn, editado",
          copy: "Una actualización de empresa anunciando una conversación sobre ciencia básica, inmunología y la investigación detrás de soluciones actuales en salud.",
          reactions: "66",
          comments: "1",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_theraresearch-cienciab%C3%A1sica-investigaci%C3%B3n-activity-7468760527238864897-MlLI",
          tags: ["Thera Research", "Ciencia básica", "Inmunología"],
        },
        {
          label: "Estudios clínicos",
          title: "Cómo comenzaron los estudios clínicos modernos",
          date: "Hace 3 semanas en LinkedIn",
          copy: "Un video educativo sobre el camino histórico desde las primeras preguntas terapéuticas hasta la evidencia estructurada en estudios clínicos modernos.",
          reactions: "22",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_sab%C3%ADas-que-los-estudios-cl%C3%ADnicos-comenzaron-activity-7467183321459081216-Nhj9",
          tags: ["Estudios clínicos", "Historia", "Evidencia"],
        },
        {
          label: "Neuroinmunología",
          title: "Parkinson e investigación inmune",
          date: "Hace 1 mes en LinkedIn",
          copy: "Un video sobre el trabajo de Rodrigo Pacheco y cómo la neuroinmunología está cambiando la forma de entender la progresión del Parkinson.",
          reactions: "36",
          comments: "2",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_neurociencia-inmunolog%C3%ADa-investigaci%C3%B3ncl%C3%ADnica-activity-7465378913473585152-n9KC",
          tags: ["Neurociencia", "Inmunología", "Innovación"],
        },
        {
          label: "Ciencia Que Transforma",
          title: "Virus, ciencia básica e impacto en salud",
          date: "Hace 1 mes en LinkedIn, editado",
          copy: "El primer capítulo de Ciencia Que Transforma destaca investigación básica, colaboración científica y el recorrido desde el descubrimiento hasta el impacto en salud pública.",
          reactions: "56",
          comments: "2",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_cienciaquetransforma-investigaci%C3%B3ncient%C3%ADfica-activity-7465115946353848320-CUuv",
          tags: ["Ciencia básica", "Salud pública", "Ciencia"],
        },
        {
          label: "Ecosistema de investigación clínica",
          title: "Cumbre de Investigación Clínica AMIIF",
          date: "Hace 1 mes en LinkedIn",
          copy: "Una republicación desde la cumbre AMIIF sobre capacidad operativa, instituciones conectadas, procesos eficientes y modelos colaborativos para investigación clínica.",
          reactions: "36",
          comments: "2",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_investigaci%C3%B3ncl%C3%ADnica-ensayoscl%C3%ADnicos-chile-activity-7461090021736067072-Gi6N",
          tags: ["Investigación clínica", "Innovación", "Ecosistema"],
        },
        {
          label: "Ciencia traslacional",
          title: "TRIMELVax y desarrollo clínico en Chile",
          date: "Hace 1 mes en LinkedIn, editado",
          copy: "Una nota que conecta los resultados de TRIMELVax con el puente desde ciencia básica hacia ejecución clínica real, regulada y bien diseñada.",
          reactions: "45",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_hace-unos-d%C3%ADas-el-10-de-abril-tuve-la-oportunidad-activity-7460362410928009216-vivw",
          tags: ["TRIMELVax", "Desarrollo clínico", "Chile"],
        },
        {
          label: "Investigación centrada en pacientes",
          title: "Las personas detrás de la investigación clínica",
          date: "Hace 1 mes en LinkedIn",
          copy: "Un recordatorio humano de que cada dato se conecta con pacientes, equipos de estudio y profesionales que trabajan con rigor y compromiso.",
          reactions: "12",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_clinicalresearch-investigacionclinica-activity-7460297964809281536-aOb6",
          tags: ["Pacientes", "Equipos", "Investigación clínica"],
        },
        {
          label: "Colaboraciones",
          title: "Visita de BUPA a Ciencia & Vida",
          date: "Hace 1 mes en LinkedIn, editado",
          copy: "Una actualización de ecosistema desde la visita de ejecutivos de BUPA a Fundación Ciencia & Vida y oficinas de Thera Research, con foco en reclutamiento, colaboración e investigación regional.",
          reactions: "",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_clinicalresearch-healthcareinnovation-activity-7457848363489624064-heTb",
          tags: ["Colaboraciones", "Innovación en salud", "LatAm"],
        },
        {
          label: "Estudios clínicos",
          title: "Día de los Estudios Clínicos e innovación en salud",
          date: "Hace 1 mes en LinkedIn",
          copy: "Un reconocimiento a la curiosidad, el rigor, participantes, investigadores, patrocinadores, centros y equipos detrás de los estudios clínicos.",
          reactions: "14",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicaltrialsday-clinicalresearch-clinicaltrials-activity-7462952560190992386-hunF",
          tags: ["Día de Estudios Clínicos", "Evidencia", "Innovación en salud"],
        },
        {
          label: "Evidencia",
          title: "El dato se vuelve insight con contexto",
          date: "Hace 1 mes en LinkedIn",
          copy: "Una breve publicación de operación clínica sobre por qué el dato por sí solo no basta y cómo el contexto conecta evidencia con ejecución real.",
          reactions: "10",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicaltrials-clinicalresearch-pharma-activity-7455590551388737536-bsSF",
          tags: ["Datos", "Operación clínica", "Pharma"],
        },
        {
          label: "Tiempos de estudio",
          title: "Ensayos más rápidos necesitan alineación",
          date: "Hace 2 meses en LinkedIn",
          copy: "Una nota concisa sobre factibilidad, protocolos realistas y compromiso de centros como ingredientes operativos para mejorar los tiempos de estudio.",
          reactions: "25",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicaltrials-clinicalresearch-cro-activity-7453442684721180672-yQuV",
          tags: ["Factibilidad", "Tiempos", "Centros"],
        },
        {
          label: "Colaboración público-privada",
          title: "Taller de visión CORFO",
          date: "Hace 2 meses en LinkedIn",
          copy: "Una actualización desde el taller de visión en investigación biomédica organizado por el programa Transforma Innovación en Salud de CORFO.",
          reactions: "21",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicaltrials-chile-innovation-activity-7452075324173000704-I5C6",
          tags: ["Chile", "Innovación", "Público-privado"],
        },
        {
          label: "Innovación en salud",
          title: "PULSO e innovación multidisciplinaria",
          date: "Hace 2 meses en LinkedIn",
          copy: "Una reflexión desde PULSO sobre cómo la innovación en salud también depende del diseño, la comunicación, la conexión con pacientes y el trabajo multidisciplinario.",
          reactions: "14",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_innovation-health-clinicalresearch-activity-7452079134719156224-jrBS",
          tags: ["Innovación", "Paciente al centro", "Chile"],
        },
        {
          label: "IA y regulación",
          title: "Inteligencia artificial en estudios clínicos",
          date: "Hace 2 meses en LinkedIn",
          copy: "Una nota regulatoria sobre trazabilidad, validación y protección de datos mientras la inteligencia artificial entra en flujos de estudios clínicos.",
          reactions: "4",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_clinicaltrials-ai-clinicalresearch-activity-7452063570571444224-HnXJ",
          tags: ["IA", "Regulación", "Estudios clínicos"],
        },
        {
          label: "Actividad de empresa",
          title: "Año nuevo 2025",
          date: "Hace 1 año en LinkedIn",
          copy: "Un saludo de empresa para 2025, con foco continuo en estudios clínicos, innovación médica, trabajo centrado en pacientes e investigación ética.",
          reactions: "5",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_newyear2025-clinicaltrials-medicalinnovation-activity-7279860081645481985-EFWe",
          tags: ["Empresa", "Estudios clínicos", "Innovación médica"],
        },
        {
          label: "Salud mental",
          title: "Día Mundial de la Lucha contra la Depresión",
          date: "Hace 1 año en LinkedIn",
          copy: "Una publicación de concientización sobre salud mental y el rol de los estudios clínicos en desarrollar terapias, herramientas y nuevas opciones para la depresión.",
          reactions: "1",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_worlddayagainstdepression-mentalhealth-activity-7284555486945816577-4gWh",
          tags: ["Salud mental", "Estudios clínicos", "Concientización"],
        },
        {
          label: "Práctica CRA",
          title: "10 claves para destacar como CRA",
          date: "Hace 1 año en LinkedIn",
          copy: "Contenido práctico para monitores de investigación clínica sobre protocolos, cumplimiento, relación con centros, resolución proactiva de problemas y seguridad de pacientes.",
          reactions: "",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_10-key-tips-to-excel-as-a-cra-in-clinical-activity-7270506239611043840-hcK1",
          tags: ["CRA", "Operación clínica", "Seguridad del paciente"],
        },
        {
          label: "Educación de participantes",
          title: "Qué ocurre al terminar la participación en un estudio",
          date: "Hace 1 año en LinkedIn",
          copy: "Contenido educativo para participantes sobre seguimiento de salud, acceso a resultados, confidencialidad y contribución a futuros tratamientos.",
          reactions: "1",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_theraresearch-clinicaltrials-activity-7267634428154195969-0jOs",
          tags: ["Participantes", "Seguimiento", "Estudios clínicos"],
        },
        {
          label: "Carreras",
          title: "Búsqueda de Clinical Research Associate",
          date: "Hace 1 año en LinkedIn",
          copy: "Una publicación de reclutamiento para un rol CRA II, CRA III o CRA Senior, enfocada en experiencia de monitoreo remoto de estudios clínicos.",
          reactions: "39",
          comments: "",
          url: "https://es.linkedin.com/posts/theraresearch-ltda_ofertadetrabajo-cra-clinicaltrials-activity-7233919781895090177-B_Rq",
          tags: ["Carreras", "CRA", "Estudios clínicos"],
        },
        {
          label: "Oncología",
          title: "Qué es el cáncer de pulmón y por qué importa",
          date: "Hace 1 año en LinkedIn",
          copy: "Una publicación de salud sobre cáncer de pulmón en Chile, estudios observacionales, modelos computacionales y ensayos adaptativos.",
          reactions: "5",
          comments: "1",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_what-is-the-most-common-type-of-cancer-activity-7230322439262552064-_GHw",
          tags: ["Cáncer de pulmón", "Oncología", "Ensayos adaptativos"],
        },
        {
          label: "Estudios clínicos",
          title: "Día Internacional de los Ensayos Clínicos 2024",
          date: "Hace 2 años en LinkedIn",
          copy: "Un reconocimiento a pacientes y profesionales que hacen posibles los estudios clínicos y ayudan a avanzar nuevos tratamientos.",
          reactions: "3",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_internationalclinicaltrialsday-healthinnovation-activity-7198454004593422336-B8Xw",
          tags: ["Estudios clínicos", "Innovación en salud", "Participantes"],
        },
        {
          label: "Educación",
          title: "Roles en los estudios clínicos",
          date: "Hace 2 años en LinkedIn",
          copy: "Contenido educativo sobre el trabajo de investigadores principales, co-investigadores, coordinadores y monitores de investigación clínica.",
          reactions: "8",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_the-roles-in-clinical-trials-activity-7193671354313756673-L30W",
          tags: ["Educación", "Equipos de estudio", "Estudios clínicos"],
        },
        {
          label: "Vacunas",
          title: "Cómo se desarrollan las vacunas",
          date: "Hace 2 años en LinkedIn",
          copy: "Una publicación por la Semana de Vacunación en las Américas que explica evaluación preclínica, respuesta inmune, estudios en animales y fases clínicas en humanos.",
          reactions: "4",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_vaccines-clinicaltrials-theraresearch-activity-7188570332130091010-J4Q7",
          tags: ["Vacunas", "Estudios clínicos", "OPS"],
        },
        {
          label: "Buenas Prácticas Clínicas",
          title: "Curso ACROCHI de Buenas Prácticas Clínicas",
          date: "Hace 5 años en LinkedIn",
          copy: "Una actualización de formación para el curso online de Buenas Prácticas Clínicas de ACROCHI, con Ximena Verdina como relatora sobre comités de ética.",
          reactions: "16",
          comments: "",
          url: "https://www.linkedin.com/posts/theraresearch-ltda_acrochi-clinicaltrials-clinicalresearch-activity-6729098011470823424--6sX",
          tags: ["BPC", "ACROCHI", "Comités de ética"],
        },
      ],
    },
    patientRegistration: {
      aria: "Registro de reclutamiento de pacientes",
      eyebrow: "Reclutamiento de pacientes",
      heading: "Registro para pacientes interesados en estudios clínicos.",
      copy: "Complete estos datos para que el equipo de Thera Research pueda revisar su consulta y contactarle por teléfono o correo electrónico.",
      stepsAria: "Información solicitada para el registro",
      steps: [
        {
          icon: UserRound,
          title: "Datos personales",
          copy: "Nombre, apellidos, teléfono y ciudad de residencia.",
        },
        {
          icon: HeartPulse,
          title: "Antecedente clínico",
          copy: "Estado de diagnóstico de cáncer y detalle informado por el paciente.",
        },
        {
          icon: ClipboardList,
          title: "Autorización",
          copy: "Permiso explícito para que el equipo contacte al paciente.",
        },
      ],
      formAria: "Formulario de reclutamiento de pacientes",
      fields: {
        firstName: {
          label: "Nombre",
          error: "Ingrese su nombre.",
        },
        lastName: {
          label: "Apellidos",
          error: "Ingrese sus apellidos.",
        },
        phone: {
          label: "Teléfono",
          error: "Ingrese un teléfono de contacto.",
        },
        city: {
          label: "Ciudad donde vive",
          error: "Ingrese su ciudad.",
        },
        diagnosed: {
          label: "¿Ha sido diagnosticado de cáncer?",
          yes: "Sí",
          no: "No",
          error: "Seleccione una respuesta.",
        },
        diagnosis: {
          label: "¿Cuál es su diagnóstico de cáncer?",
          error: "Ingrese el diagnóstico informado.",
        },
        consent: {
          label:
            "Autorizo a Thera Research a contactarme y enviarme información por correo electrónico o teléfono.",
          error: "Debe autorizar el contacto para enviar el registro.",
        },
      },
      status: {
        loadingLabel: "Enviando registro",
        empty: "Complete los campos requeridos para enviar el registro.",
        error: "Complete los datos requeridos.",
        success:
          "Registro enviado. El equipo de Thera Research podrá revisar su información.",
      },
      submit: "Enviar registro",
      iframeTitle: "Envío del reclutamiento de pacientes",
    },
    operatingSignals: [
      { label: "Modelo operativo", value: "Coordinación local de centros" },
      {
        label: "Sectores patrocinadores",
        value: "Pharma, biotech, genéricos, OTC, dispositivos",
      },
      {
        label: "Alcance del estudio",
        value: "Planificación, ejecución, informes",
      },
      {
        label: "Línea regulatoria",
        value: "Presentaciones y puesta en marcha",
      },
    ],
    contact: {
      eyebrow: "Contacto",
      heading: "Inicie su próximo estudio clínico con Thera Research.",
      copy: "Contacte a un equipo preparado para impulsar la coordinación entre patrocinador y centro, con el objetivo de reducir plazos y mejorar el éxito del estudio.",
    },
    contactForm: {
      aria: "Solicitud de contacto para estudio clínico",
      fields: {
        name: {
          label: "Nombre",
          placeholder: "Patrocinador o líder del estudio",
          hint: "Se usa solo para identificar la solicitud de contacto.",
          error: "Ingrese su nombre.",
        },
        email: {
          label: "Correo electrónico",
          placeholder: "nombre@empresa.com",
          hint: "Se recomienda un correo corporativo.",
          error: "Ingrese un correo electrónico válido.",
        },
        message: {
          label: "Contexto del estudio",
          placeholder:
            "Área terapéutica, centros, plazos o necesidades de reclutamiento",
          hint: "Incluya el alcance mínimo útil para revisar factibilidad.",
          error: "Agregue el contexto del estudio.",
        },
      },
      status: {
        loadingLabel: "Preparando solicitud de contacto",
        empty: "Complete los campos para preparar la solicitud de contacto.",
        error: "Todos los campos son requeridos para preparar la solicitud.",
        success:
          "Solicitud de contacto preparada. El siguiente paso es conectar este formulario a CRM o correo.",
      },
      submit: "Preparar solicitud",
    },
    footer: {
      copy: "Organización de investigación clínica que apoya planificación, ejecución, informes, monitoreo, coordinación regulatoria y reclutamiento de pacientes.",
      label: "Organización de investigación clínica",
      ctaEyebrow: "Ejecución clínica local",
      ctaHeading: "Planifique la próxima ruta de estudio con Thera Research.",
      ctaCopy:
        "Comience con el contexto del estudio, necesidades de reclutamiento, centros o plazos que requieren responsabilidad local en Chile.",
      primaryCta: "Iniciar un estudio",
      secondaryCta: "Ver actividad",
      routesLabel: "Secciones del sitio",
      contactLabel: "Contacto directo",
      sourceLabel: "Actividad reciente",
      sourceCopy:
        "Actualizaciones de LinkedIn, noticias de empresa y notas de investigación clínica.",
      legal: "Thera Research Ltda. Operación de investigación clínica en Chile.",
    },
  },
} as const;

export type SiteContent = (typeof siteContent)[Language];

export const images = {
  hero: assetPath("assets/clinical-cells.jpg"),
  lab: assetPath("assets/lab-workstation.jpg"),
  monitoring: assetPath("assets/pipette-monitoring.jpg"),
  patients: assetPath("assets/patient-recruitment.jpg"),
};

export const clinicalIntelligenceImages = {
  hero: assetPath("assets/thera-hero-clinical-operations.webp"),
  lab: assetPath("assets/thera-v5-regulatory-activation.webp"),
  monitoring: assetPath("assets/thera-v5-monitoring-cra.webp"),
  patients: assetPath("assets/thera-v5-patient-recruitment.webp"),
};
